context:
  version: "0.5.0"
  python_min: "3.11"

package:
  name: spaday-perspective
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/spaday-perspective/spaday_perspective-${{ version }}.tar.gz
  sha256: 39ae04791c8ad687ecb3458ca4cbd763d3c523070ae88700c160f3d8224f3166

build:
  number: 0
  noarch: python
  script:
    env:
      SKIP_HATCH_JS: "1"
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-js
  run:
    - python >=${{ python_min }}
    - perspective >=5.2,<5.3
    - spaday >=0.6.0

tests:
  - python:
      imports:
        - spaday_perspective
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Perspective for spaday
  homepage: https://github.com/1kbgz/spaday-perspective
  repository: https://github.com/1kbgz/spaday-perspective

extra:
  recipe-maintainers:
    - timkpaine
